ex = input('Escreva algo: ')
print('O tipo primitivo deste valor é:', type(ex))
print('Só tem espaços?', ex.isspace(),)
print('É um número?', ex.isnumeric())
print('É alfabético?', ex.isalpha())
print('É alfabumérico?', ex.isalnum())
print('Está em maiúsculas?', ex.isupper())
print('Está em minúsculas?', ex.islower())
print('Está capitalizada?', ex.istitle())
