n = int(input('Digite um número para ver sua tabuada: '))
print(13*'-')
print('{}  X {:2} = {}'.format(1, n, 1*n))
print('{}  x {:2} = {}'.format(2, n, 2*n))
print('{}  x {:2} = {}'.format(3, n, 3*n))
print('{}  x {:2} = {}'.format(4, n, 4*n))
print('{}  x {:2} = {}'.format(5, n, 5*n))
print('{}  x {:2} = {}'.format(6, n, 6*n))
print('{}  x {:2} = {}'.format(7, n, 7*n))
print('{}  x {:2} = {}'.format(8, n, 8*n))
print('{}  x {:2} = {}'.format(9, n, 9*n))
print('{} x  {} = {}'.format(10, n, 10*n))
print(13*'-')